### ISSUE TITLE
Film model video attribute.

### ISSUE THREAD

**Issue by ghost** [Romeno/KinaKipaWeb#24]
Should it be a `FileField` or `URLField` of vk-video?
`
 video = FileField(storage=VIDEO_STORAGE, help_text="Відэа")
`
[https://github.com/Romeno/KinaKipaWeb/blob/master/KinaKipa/models.py](../models.py)

**Comment by UnVoiding** [comment]
It should be URLFiled

**Comment by ghost** [comment]
I see. Probably, html like this isn't necessary: 
<iframe width="607" height="360" src="https://www.youtube.com/embed/qd9RWzAa5cM" frameborder="0" allowfullscreen></iframe>

We'd rather wrap it later.
