### ISSUE TITLE
Сбор информации по фильмам мовананова

### ISSUE THREAD

**Issue by UnVoiding** [Romeno/KinaKipaWeb#3]
Используя сайт [мовананова](http://www.movananova.by/medyateka/videa-medyateka/), написать краулер для получения информации по уже собранным кем-то фильмам. 

Для написания можно использовать:

- Модуль [requests](http://docs.python-requests.org/en/master/)
- Модуль [BeautifulSoup (bs4)](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- Другие модули позволяющие краулить сайты

Информацию сохранить в [csv](https://ru.wikipedia.org/wiki/CSV) файл

**Comment by ghost** [comment]
Crawled film-links in json format:
{"bajeviki/": ["http://www.movananova.by/medyateka/dryzhanni-pa-belarusku.html", "http://www.movananova.by/medyateka/zakaznoe-zabojstva.html",
... ]
}
